
platform :ios, '9.0'

target 'RxSVP_Example' do
  use_frameworks!

#  pod 'RxSwift'
#  pod 'RxCocoa'
  pod 'NSObject+Rx'
  
  pod 'RxSVP', :path => '../'
  
  target 'RxSVP_Tests' do
    inherit! :search_paths
  end
end
