use_frameworks!

platform :ios, '9.0'

target 'RxSVP_Example' do
  
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'NSObject+Rx'
  pod 'SVProgressHUD'
  
  target 'RxSVP_Tests' do
    inherit! :search_paths
  end
end
